# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(400, 500)
        login.setStyleSheet("")
        # Remove window frame
        login.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        login.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.label = QtWidgets.QLabel(parent=login)
        self.label.setGeometry(QtCore.QRect(20, 20, 361, 451))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(107, 134, 134, 255), stop:1 rgba(220, 242, 242,255));\n"
"border-radius: 10px;\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=login)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.unEdit = QtWidgets.QLineEdit(parent=login)
        self.unEdit.setGeometry(QtCore.QRect(50, 200, 291, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.unEdit.setFont(font)
        self.unEdit.setStyleSheet("background-color: transparent;\n"
"border: 2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(0, 0, 0, 200);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.unEdit.setObjectName("unEdit")
        self.passEdit = QtWidgets.QLineEdit(parent=login)
        self.passEdit.setGeometry(QtCore.QRect(50, 260, 291, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.passEdit.setFont(font)
        self.passEdit.setStyleSheet("background-color: transparent;\n"
"border: 2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(0, 0, 0, 200);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.passEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passEdit.setObjectName("passEdit")
        self.pushButton = QtWidgets.QPushButton(parent=login)
        self.pushButton.setGeometry(QtCore.QRect(50, 350, 291, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
"    background-color: #A0B0C1;\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-width: 4px;\n"
"    border-radius: 10px;\n"
"    border-color: #6b8686;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton#pushButton:hover {\n"
"    background-color: #b7cadd; \n"
"}\n"
"QPushButton#pushButton:pressed {\n"
"    background-color:#319e20; \n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Form"))
        self.label_2.setText(_translate("login", "P R I J A V A"))
        self.unEdit.setPlaceholderText(_translate("login", "  korisničko ime"))
        self.passEdit.setPlaceholderText(_translate("login", "  lozinka"))
        self.pushButton.setText(_translate("login", "P r i j a v i  s e"))
